dist: xenial
language: java
jdk:
  - openjdk8
  - openjdk11
cache:
  directories:
    - $HOME/.m2
install: ./mvnw -B install -Dgpg.skip=true
after_success:
  - ./mvnw -B jacoco:report coveralls:report
